using System.ComponentModel.DataAnnotations;

namespace NoCrast.Shared.Model
{
    public class ModelItem
    {
        /// <summary>
        /// Public id of the object assigned by server
        /// </summary>
        [Required]
        public string Id { get; set; }
        /// <summary>
        /// Temporary id generated by client. It should be used for
        /// the new objects create on client before the have been
        /// "posted" to the server. Once it is posted to the server,
        /// server will reply with Id and ClientId can be dropped
        /// (set to null).
        /// </summary>
        public string ClientId { get; set; }
    }
}
